server:
  port: 8627

spring:
  application:
    name: xyf_web
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_ft
      #      username: db_ft
      #      password: ENnTkcAZGFbGyT8L
      username: root
      password: 123456

# 开启MyBatis的自动驼峰命名映射
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.xyf.mapper: debug